version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - ../analytics_engineering/:/usr/app
      - ~/.dbt/:/root/.dbt/
      - /Users/ramisu/.google/credentials/google_credentials.json:/secrets/google_credentials.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/google_credentials.json
    network_mode: host
