
links:
  - https://archivo.datos.cdmx.gob.mx/C5/incidentes_viales/inViales_2022_2024.csv
  - https://archivo.datos.cdmx.gob.mx/C5/incidentes_viales/inViales_2019_2021.csv
  - https://archivo.datos.cdmx.gob.mx/C5/incidentes_viales/inViales_2016_2018.csv
  - https://archivo.datos.cdmx.gob.mx/C5/incidentes_viales/inViales_2014_2015.csv
  - https://datos.cdmx.gob.mx/dataset/a6d1d483-65d2-4ed9-9687-1932eb0cf70f/resource/49b5360c-5922-46bd-b4f8-ed0225d5ddbf/download/diccionario-incidentes-viales-c5.xlsx