version: 2

models:
  - name: fact_table
    description: ""
    columns:
      - name: id
        data_type: string
        description: "Unique id for each incident"
        tests:
          - not_null:
              severity: warn
          - unique:
              severity: warn


      - name: creation_date
        data_type: date
        description: "date of incident registered"

      - name: creation_hour
        data_type: time
        description: "hour of incident registered"

      - name: latitude
        data_type: float64
        description: "latitud where incident take place"
        tests:
          - not_null:
              severity: warn

      - name: longitud
        data_type: float64
        description: "longitud where incident take place"
        tests:
          - not_null:
              severity: warn


      - name: index_week_day
        data_type: string
        description: "Index of week of day, take dim_weekday for reference"
        tests:
          - not_null:
              severity: warn


      - name: index_suburb
        data_type: int64
        description: "Index of suburb, take dim_suburb for reference"
        tests:
          - not_null:
              severity: warn

      - name: index_type_incident
        data_type: int64
        description: "Index of type_incident, take dim_incident for reference"
        tests:
          - not_null:
              severity: warn

      - name: index_town_hall
        data_type: int64
        description: "Index of town hall, take dim_townhall for reference"
        tests:
          - not_null:
              severity: warn

      - name: index_reception_medium
        data_type: int64
        description: "Index of reception medium, take dim_reception_medium for reference"
        tests:
          - not_null:
              severity: warn

      - name: index_incident_classification
        data_type: int64
        description: "Index of incident classification, take dim_incident_classfication for reference"
        tests:
          - not_null:
              severity: warn

      - name: index_incident
        data_type: int64
        description: "Index of incident, take dim_incident for reference"
        tests:
          - not_null:
              severity: warn
